[phases.setup]
cmds = [
  "apt-get update",
  "apt-get install -y python3 python3-pip python3-dev",
  "ln -sf /usr/bin/python3 /usr/bin/python"
]

[phases.install]
cmds = ["pip3 install -r requirements.txt"]

[start]
cmd = "python app.py"
